"use strict";
var eycompo = eycompo || {};
eycompo ={
		commonnav :()=>{
			return '<nav class="navbar navbar-inverse navbar-default" role="navigation" id="comnav" data-spy="affix" data-offset-top="525" style="width: 100%; height:50px; background-color: #fafafa; border: none; border-bottom: 1px solid; border-color: #ddd; border-radius: 0px; margin-bottom:0px;">	  '
			+'<div class="container-fluid">'
			+'<ul class="nav navbar-nav">'
			+'      <li id="home"><a href="#">HOME</a></li>'
			+'      <li id="ocean"><a href="#">OCEAN</a></li>'
			+'      <li id="river"><a href="#">RIVER</a></li>'
			+'      <li id="hotel"><a href="#">HOTEL</a></li>'
			+'      <li id="aquagram"><a href="#">AQUAGRAM</a></li>'
			+'      <li id="mypage"><a href="#">MYPAGE</a></li>'
			+'      <li id="logout"><a href="#">LOGOUT</a></li>'
			+'</ul>'
			+'</div>'
			+'</nav>'
		},
		main_container : ()=>{
			return'<div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-dial"></span></span>'
			+'            <h3>Create An Account</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
			+'        '
			+'        <div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-search"></span></span>'
			+'            <h3>Search Desired Job</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
			+'        '
			+'        <div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-printer"></span></span>'
			+'            <h3>Send Your Resume</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
			+'        '
			+'        <div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-dial"></span></span>'
			+'            <h3>Create An Account</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
			+'        '
			+'        <div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-search"></span></span>'
			+'            <h3>Search Desired Job</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
			+'        '
			+'        <div class="col-md-4 col-sm-4">'
			+'          <div class="features-content">'
			+'            <span class="box1"><span aria-hidden="true" class="icon-printer"></span></span>'
			+'            <h3>Send Your Resume</h3>'
			+'            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid ut labore et dolore magna aliqua.</p>'
			+'          </div>'
			+'        </div>'
		},
		
		search_bar : ()=>{
			return '<section class="newsletter">'
			+'      <div class="container">'
			+'        <div class="row">'
			+'          <div class="col-md-10 col-sm-10 col-md-offset-1 col-sm-offset-1">'
			+'          <h2>도시명을 입력하세요 </h2>'
			+'          <div class="input-group">'
			+'            <input type="text" class="form-control" placeholder="도시명만 쓰세요...">'
			+'            <span class="input-group-btn">'
			+'              <button type="button" class="btn btn-default">SEARCH</button>'
			+'            </span>'
			+'          </div>'
			+'          </div>'
			+'        </div>'
			+'      </div>'
			+'    </section>'
		},
		main:()=>{
			return '<!-- 검색창 -->'
		    +'<div>'
		    +'<section id="search_content" class="main-banner" style="background:#242c36 url(/web/resources/img/reservation/slider-01.jpg) no-repeat">'
		      +'<div class="container">'
		        +'<div class="caption">'
		          +'<h2>PLAN YOUR NEXT FISHING</h2>'
		          +'<form>'
		            +'<fieldset>'
		              +'<div class="col-md-4 col-sm-4 no-pad">'
		                +'<input type="text" class="form-control border-right" placeholder="도시명" />'
		              +'</div>'
		              +'<div class="col-md-3 col-sm-3 no-pad">'
		                +'<select class="selectpicker border-right">'
		                  +'<option>날짜 선택</option>'
		                  +'<option>0 Year</option>'
		                  +'<option>1 Year</option>'
		                  +'<option>2 Year</option>'
		                  +'<option>3 Year</option>'
		                  +'<option>4 Year</option>'
		                  +'<option>5 Year</option>'
		                  +'<option>6 Year</option>'
		                  +'<option>7 Year</option>'
		                  +'<option>8 Year</option>'
		                  +'<option>9 Year</option>'
		                 +'<option>10 Year</option>'
		                +'</select>'
		              +'</div>'
		              +'<div class="col-md-3 col-sm-3 no-pad">'
		                +'<select class="selectpicker">'
		                  +'<option>인원 선택</option>'
		                  +'<option>1</option>'
		                  +'<option>2</option>'
		                  +'<option>3</option>'
		                  +'<option>4 + </option>'
		                +'</select>'
		              +'</div>'
		              +'<div class="col-md-2 col-sm-2 no-pad">'
		                +'<input type="submit" class="btn seub-btn" value="SEARCH" />'
		              +'</div>'
		            +'</fieldset>'
		          +'</form>'
		        +'</div>'
		      +'</div>'
		    +'</section>'
		    +'</div>'
		    +'<!-- 검색창  끝-->'
		    +''
		    +'<!-- 메인 화면  -->'
		    +'<div class="features">'
		      +'<div id="main-container" class="container">'

		      +'</div>'
		    +'</div>'
		}
		
};