"use strict";
var eycompo = eycompo || {};
eycompo ={
		commonnav :()=>{
			return '<nav class="navbar navbar-inverse navbar-default" role="navigation" id="comnav" data-spy="affix" data-offset-top="525" style="width: 100%; height:50px; background-color: #fafafa; border: none; border-bottom: 1px solid; border-color: #ddd; border-radius: 0px; margin-bottom:0px;">	  '
			+'<div class="container-fluid">'
			+'<ul class="nav navbar-nav">'
			+'      <li id="home"><a href="#">HOME</a></li>'
			+'      <li id="ocean"><a href="#">OCEAN</a></li>'
			+'      <li id="river"><a href="#">RIVER</a></li>'
			+'      <li id="hotel"><a href="#">HOTEL</a></li>'
			+'      <li id="aquagram"><a href="#">AQUAGRAM</a></li>'
			+'      <li id="mypage"><a href="#">MYPAGE</a></li>'
			+'      <li id="logout"><a href="#">LOGOUT</a></li>'
			+'</ul>'
			+'</div>'
			+'</nav>'
		},

		search_bar : ()=>{
			return '<section class="newsletter">'
			+'      <div class="container">'
			+'        <div class="row">'
			+'          <div class="col-md-10 col-sm-10 col-md-offset-1 col-sm-offset-1">'
			+'          <h2>도시명을 입력하세요 </h2>'
			+'          <div class="input-group">'
			+'            <input type="text" class="form-control" placeholder="도시명만 쓰세요...">'
			+'            <span class="input-group-btn">'
			+'              <button type="button" class="btn btn-default">SEARCH</button>'
			+'            </span>'
			+'          </div>'
			+'          </div>'
			+'        </div>'
			+'      </div>'
			+'    </section>'
		},
		
		main_search:()=>{
			return '<!-- 검색창 -->'
		    +'<div>'
		    +'<section id="search_content" class="main-banner" style="background:#242c36 url(/web/resources/img/reservation/ocean.jpg) no-repeat">'
		      +'<div class="container">'
		        +'<div class="caption">'
		          +'<h2>PLAN YOUR NEXT FISHING</h2>'
		          +'<form>'
		            +'<fieldset>'
		              +'<div class="col-md-4 col-sm-4 no-pad">'
		              +'<input type="text" class="form-control border-right" placeholder="도시명" />'
		              +'</div>'
		              +'<div class="col-md-3 col-sm-3 no-pad">'
		              +'<input type="text" class="form-control border-right id="datepicker">'
		              +'</div>'
		              +'<div class="col-md-3 col-sm-3 no-pad">'
		                +'<select class="selectpicker">'
		                  +'<option>인원 선택</option>'
		                  +'<option>1</option>'
		                  +'<option>2</option>'
		                  +'<option>3</option>'
		                  +'<option>4 + </option>'
		                +'</select>'
		              +'</div>'
		              +'<div class="col-md-2 col-sm-2 no-pad">'
		                +'<input type="submit" class="btn seub-btn" value="SEARCH" />'
		              +'</div>'
		            +'</fieldset>'
		          +'</form>'
		        +'</div>'
		      +'</div>'
		    +'</section>'
		    +'</div>'
		    +'<!-- 검색창  끝-->'
		    +''
		    +'<!-- 메인 화면  -->'
		    +'</br>'
		    +'</br>'
		    +'<div class="features">'
		    +'<div id="main-container" class="container">'
		    +'</div>'
		    +'</div></br></br>'
		},
		
		item_container : ()=>{
			return '<div class="col-md-8">'
			+'					<div class="row">'
			+'						<div class="basic-information">'
			+'							<div class="col-md-12">'
			+'                        <img src="/web/resources/img/reservation/joy.jpg" alt="" class="img-responsive">'
			+'							</div>'
			+'							<ul class="social">'
			+'								<li><a href="" class="facebook"><i class="fa fa-facebook"></i>Facebook</a></li>'
			+'								<li><a href="" class="google"><i class="fa fa-google-plus"></i>Google Plus</a></li>'
			+'								<li><a href="" class="twitter"><i class="fa fa-twitter"></i>Twitter</a></li>'
			+'								<li><a href="" class="linkedin"><i class="fa fa-linkedin"></i>Linked In</a></li>'
			+'								<li><a href="" class="instagram"><i class="fa fa-instagram"></i>Instagram</a></li>'
			+'							</ul>'
			+'							<div class="panel panel-default">'
			+'								<div class="panel-heading">'
			+'									<i class="fa fa-user fa-fw"></i> About Me'
			+'								</div>'
			+''
			+'						<!-- /.panel-heading -->'
			+'								<div class="panel-body">'
			+'								<div id="datepicker"></div>'
			+'                        <img src="https://static.collectui.com/shots/3633221/date-picker-large" alt="" class="img-responsive"></br></br>'
			+'								</div>'
			+'							</div>'
			+'							'
			+'							<div class="panel panel-default">'
			+'								<div class="panel-heading">'
			+'									<i class="fa fa-leaf fa-fw"></i> Responsibilities:'
			+'								</div>'
			+'													<!-- /.panel-heading -->'
			+'								<div class="panel-body">'
			+'                        <img src="http://image.zdnet.co.kr/2018/06/08/imc_IqyKj7sDWtLpRcli.jpg" alt="" class="img-responsive"></br></br>'
			+'								</div>'
			+'							</div>'
			+'							'
			+'							<div class="panel panel-default">'
			+'								<div class="panel-heading">'
			+'									<i class="fa fa-cog fa-fw"></i> Skills'
			+'								</div>'
			+'													<!-- /.panel-heading -->'
			+'								<div class="panel-body">'
			+'								<ul>'
			+'									<li>Software testing in a Web Applications/Mobile environment.</li>'
			+'									<li>Software Test Plans from Business Requirement Specifications for test engineering group.</li>'
			+'									<li>Software testing in a Web Applications environment.</li>'
			+'									<li>Translate designs into responsive web interfaces</li>'
			+'									<li>Software testing in a Web Applications/Mobile environment.</li>'
			+'								</ul>'
			+'								<span class="service-tag">Web Design</span>'
			+'								<span class="service-tag">Graphics</span>'
			+'								<span class="service-tag">Development</span>'
			+'								<span class="service-tag">App design</span>'
			+'								<span class="service-tag">IOS Apps</span>'
			+'								<span class="service-tag">CMS Development</span>'
			+'								</div>'
			+'							</div>'
			+'						</div>'
			+'					</div>'
			+'				</div>'
			+'							</br><div class="col-md-4">'
			+'							<div class="panel panel-default">'
			+'								<div class="panel-heading">'
			+'								<div class="profile-content">'
			+'										<h2>Daniel Duke<span>Web designer</span></h2>'
			+'										<p>Soft Techi Infoteck Pvt.</p>'
			+'										<ul class="information">'
			+'											<li><span>Name:</span>Daniel Duke</li>'
			+'											<li><span>Email:</span>daniel-duke@gmail.com</li>'
			+'											<li><span>Mobile:</span>+91 548 576 8579</li>'
			+'											<li><span>Company:</span>Soft Techi Infoteck Pvt.</li>'
			+'											<li><span>Date of Birth:</span>10 July 1990</li>'
			+'										</ul>'
			+'									</div>'
			+'									</div>'
			+'									</div>'
			+'								</div>'
			+'			<div class="col-md-4 col-sm-4">'
			+'         	 <div class="package-box">'
			+'            <div class="package-header">'
			+'              <i class="fa fa-cube" aria-hidden="true"></i>'
			+'              <h3>Premium</h3>'
			+'            </div>'
			+'            <div class="package-info">'
			+'              <ul>'
			+'              <li>3 Designs</li>'
			+'              <li>3 PSD Designs</li>'
			+'              <li>4 color Option</li>'
			+'              <li>10GB Disk Space</li>'
			+'              <li>Full Support</li>'
			+'              </ul>'
			+'            </div>'
			+'            <div class="package-price">'
			+'              <h2><sup>$ </sup>170<sub>/Month</sub></h2>'
			+'            </div>'
			+'            <button type="submit" class="btn btn-package">SELECT</button>'
			+'          </div>'
			+'        </div>'
		}
		
};