/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-05-01 09:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write(" <link rel=\"shortcut icon\" href=\"/web/resources/favicon/favicon.ico\">\n");
      out.write(" <script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write(" <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- datepicker -->\n");
      out.write("<input type=\"text\" id=\"datepicker2\">\n");
      out.write("\n");
      out.write(" <!--  modal --->\n");
      out.write("<div id=\"id01\" class=\"modal\">\n");
      out.write("  <div class=\"modal-content animate\" action=\"#\">\n");
      out.write("    <div class=\"imgcontainer raw\">\n");
      out.write("      <span class=\"close1\" title=\"Close Modal\">&times;</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <label for=\"uname\"><b>Username</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Username\" name=\"uname\" id=\"userid\" required>\n");
      out.write("\n");
      out.write("      <label for=\"psw\"><b>Password</b></label>\n");
      out.write("      <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" id=\"password\" required>\n");
      out.write("      <button id=\"login\" type=\"submit\">Login</button>     \n");
      out.write("      <button id=\"kakao\"><img src=\"/web/resources/img/homeimg/main/kakao-login.png\" alt=\"\" width=\"100%\"></button>  \n");
      out.write("      <label>\n");
      out.write("        <input type=\"checkbox\" checked=\"checked\" name=\"remember\"> Remember me\n");
      out.write("      </label>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- modal-2 -->\n");
      out.write("<div id=\"myModal\" class=\"modal fade\" role=\"dialog\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("    <!-- Modal content-->\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Modal Header</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <p>Some text in the modal.</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- modal-2 end-->\n");
      out.write("\n");
      out.write(" <div id=\"wrapper\" class=\"container-fluid\">\n");
      out.write(" \n");
      out.write("<div class=\"container-fluid\">\n");
      out.write(" <!-- login -->\t\n");
      out.write(" <div id=\"loginbar\"><button id=\"loginbtn\">Login</button></div>\n");
      out.write("\t<!-- main_video -->\n");
      out.write("    <div class=\"hero-section\">\n");
      out.write("   <section class=\"vdosection\">\n");
      out.write("  <div class=\"overlay-wcs\"></div>\n");
      out.write("  <video playsinline=\"playsinline\" autoplay=\"autoplay\" muted=\"muted\" loop=\"loop\">\n");
      out.write("    <source src=\"/web/resources/video/nakuh_main.mp4\" type=\"video/mp4\">\n");
      out.write("  </video>\n");
      out.write("  <div class=\"container h-100\">\n");
      out.write("    <div class=\"d-flex h-100 text-center align-items-center\">\n");
      out.write("      <div class=\"w-100 text-white\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"space-medium\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8\n");
      out.write("               col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"mb60 text-center section-title\">\n");
      out.write("                        <!-- section title start-->\n");
      out.write("                        <h1>Our Services</h1>                   \n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.section title start--->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"service-block text-center\">\n");
      out.write("                        <!-- service block -->\n");
      out.write("                        <div class=\"service-img \">\n");
      out.write("                            <!-- service img -->\n");
      out.write("                            <a id=\"ocean\" href=\"#\"><img src=\"/web/resources/img/homeimg/main/oceanimg.JPG\" class=\"img-responsive moveimg\"> </a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- service img -->\n");
      out.write("                        <div class=\"service-content\">\n");
      out.write("                            <!-- service content -->\n");
      out.write("                            <h2><a href=\"#\" class=\"title\">선상</a></h2>                           \n");
      out.write("                        </div>\n");
      out.write("                        <!-- service content -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.service block -->\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"service-block text-center\">\n");
      out.write("                        <!-- service block -->\n");
      out.write("                        <div class=\"service-img\">\n");
      out.write("                            <!-- service img -->\n");
      out.write("                            <a id=\"river\" href=\"#\"><img src=\"/web/resources/img/homeimg/main/freshwaterimg.JPG\" class=\"img-responsive moveimg\"> </a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- service img -->\n");
      out.write("                        <div class=\"service-content\">\n");
      out.write("                            <!-- service content -->\n");
      out.write("                            <h2><a href=\"#\" class=\"title\">민물</a></h2>              \n");
      out.write("                        </div>\n");
      out.write("                        <!-- service content -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.service block -->\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"service-block text-center\">\n");
      out.write("                        <!-- service block -->\n");
      out.write("                        <div class=\"service-img\">\n");
      out.write("                            <!-- service img -->\n");
      out.write("                            <a id=\"hotel\" href=\"#\"><img src=\"/web/resources/img/homeimg/main/hotelimg.JPG\" class=\"img-responsive moveimg\"> </a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- service img -->\n");
      out.write("                        <div class=\"service-content\">\n");
      out.write("                            <!-- service content -->\n");
      out.write("                            <h2><a href=\"#\" class=\"title\">숙박</a></h2>                           \n");
      out.write("                        </div>\n");
      out.write("                        <!-- service content ----->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.service block -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row\">\n");
      out.write("\t\t  <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\t\t   <section class=\"vdosection\">\n");
      out.write("\t\t  <div id=\"aqua\" class=\"overlay-wcs\"></div>\n");
      out.write("\t\t  <video playsinline=\"playsinline\" autoplay=\"autoplay\" muted=\"muted\" loop=\"loop\">\n");
      out.write("\t\t    <source src=\"/web/resources/video/aquarium.mp4\" type=\"video/mp4\">\n");
      out.write("\t\t  </video>\n");
      out.write("\t\t  <div class=\"container h-100\">\n");
      out.write("\t\t    <div class=\"d-flex h-100 text-center align-items-center\">\n");
      out.write("\t\t      <div class=\"w-100 text-white\">\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t</div>    \n");
      out.write("    </div>\n");
      out.write("    <div class=\"space-medium bg-light\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8\n");
      out.write("               col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"mb60 text-center section-title\">\n");
      out.write("                        <!-- section title start-->\n");
      out.write("                        <h1>our recent projects</h1>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.section title start-->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-1.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-2.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-3.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-4.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-5.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\n");
      out.write("                    <div class=\"project-img mb30\">\n");
      out.write("                        <a href=\"service-detail.html\" class=\"imghover\"><img src=\"/web/resources/img/homeimg/project-pic-6.jpg\" class=\"img-responsive\" alt=\"Interior Design Website Templates Free Download\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center  \"> <a href=\"service-detail.html\" class=\"btn btn-default\">view all projects</a> </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"space-medium\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"section-title mb60 text-center\">\n");
      out.write("                        <!-- section title start-->\n");
      out.write("                        <h1>Why choose uS?</h1>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.section title start-->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("                    <div class=\"outline pinside30 text-center mb30\">\n");
      out.write("                        <div class=\"mb30\"> <img src=\"/web/resources/img/homeimg/creative-ideas.png\" class=\"\" alt=\"Interior Design Website Templates Free Download\"> </div>\n");
      out.write("                        <div class=\"\">\n");
      out.write("                            <h2>Creative Ideas </h2>\n");
      out.write("                            <p>Phasellus hendrerit mauris vitae odio suscip max pius donec aconsequat.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("                    <div class=\"outline pinside30 text-center mb30\">\n");
      out.write("                        <div class=\"mb30\"> <img src=\"/web/resources/img/homeimg/modern-technology.png\" class=\"\" alt=\"Interior Design Website Templates Free Download\"> </div>\n");
      out.write("                        <div class=\"\">\n");
      out.write("                            <h2>Modern technology</h2>\n");
      out.write("                            <p>Morbi convallis nisl at commodo tem orut libero utnisi lacinia limana.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("                    <div class=\"outline pinside30 text-center mb30\">\n");
      out.write("                        <div class=\"mb30\"> <img src=\"/web/resources/img/homeimg/design-creativity.png\" class=\"\" alt=\"Interior Design Website Templates Free Download\"> </div>\n");
      out.write("                        <div class=\"\">\n");
      out.write("                            <h2>Design &amp; Creativity</h2>\n");
      out.write("                            <p>Sednunc sagit phasellus mitortor con equat hendrerit maue odi.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"space-medium\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"section-title mb40 text-center\">\n");
      out.write("                        <!-- section title start-->\n");
      out.write("                        <h1>Our Client Says</h1>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.section title start-->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"testimonial-block bg-light pinside30\">\n");
      out.write("                        <div class=\"quote-left\"> <i class=\"fa fa-quote-left\"></i> </div>\n");
      out.write("                        <div class=\"testimonial-content\">\n");
      out.write("                            <p>\"They are talented &amp; creative. I have never seen a better designer on the this market. ecommended to all! If you need to build powerfully,contact them immediately ARCHONE design have worked on two stunning projects at our School, We were fortunate to have his vision breathe new life into a small, bare and underused courtyard in the centre of our brand new building. Within 4weeks and his team had transformed a poor quality space into a rich and vibrant courtyard garden, now enjoyed all day, every day by staff and pupils. Both projects have been well managed, within budget and worth every penny of our investment.We greatly look forward to working with him and his team again in the future.”</p>\n");
      out.write("                            <div class=\"testimonial-info\"> <span class=\"testimonial-name\">- Ruby Burns</span> <span class=\"testimonial-meta\">Market research analyst</span> </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"footer\">\n");
      out.write("        <!-- footer-->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                    <div class=\"footer-widget\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default btn-lg\" id=\"adminbtn\">관리자</button></div>\n");
      out.write("                        <p>Phasellus hendrerit mauris vitae odio suscip pimus donec consequat cursus viverra varius natoque penatibus magnis dis parturient.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                    <div class=\"footer-widget\">\n");
      out.write("                        <!-- social block -->\n");
      out.write("                        <h3 class=\"widget-title\">Our Address</h3>\n");
      out.write("                        <p>1309 Roosevelt Wilson Lane\n");
      out.write("                            <br> Colton, CA 92324</p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.social block -->\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-3 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"footer-widget\">\n");
      out.write("                        <!-- newsletter block -->\n");
      out.write("                        <h3 class=\"widget-title\">e-mail Us</h3>\n");
      out.write("                        <p>info@yourwebsitedomain.com</p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- newsletter block -->\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-3 col-sm-12 col-xs-12\">\n");
      out.write("                    <div class=\"footer-widget\">\n");
      out.write("                        <!-- newsletter block -->\n");
      out.write("                        <h3 class=\"widget-title\">Call us</h3>\n");
      out.write("                        <p>180-874-5234</p>\n");
      out.write("                        <p>180-752-3957</p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- newsletter block -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    \n");
      out.write("    <!-- /.footer-->\n");
      out.write("    <div class=\"tiny-footer\">\n");
      out.write("        <!-- tiny footer block --->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-7 col-md-7 col-sm-7 col-xs-12\">\n");
      out.write("                    <div class=\"copyright-content\">\n");
      out.write("                       Shared by <i class=\"fa fa-love\"></i><a href=\"https://bootstrapthemes.co\">BootstrapThemes</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-5 col-md-5 col-sm-5 col-xs-12\">\n");
      out.write("                    <div class=\"footer-social\">\n");
      out.write("                        <ul class=\"listnone\">\n");
      out.write("                            <li> <a href=\"#\"><i class=\"fa fa-facebook-square\"></i></a> </li>\n");
      out.write("                            <li> <a href=\"#\"><i class=\"fa fa-twitter-square\"></i></a> </li>\n");
      out.write("                            <li> <a href=\"#\"><i class=\"fa fa-google-plus-square\"></i></a> </li>\n");
      out.write("                            <li> <a href=\"#\"><i class=\"fa fa-youtube-square\"></i></a> </li>\n");
      out.write("                            <li> <a href=\"#\"><i class=\"fa fa-pinterest-square\"></i></a> </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<!-- reservationjs -->\n");
      out.write("<script src=\"/web/resources/js/reservation/vendor/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"/web/resources/js/reservation/vendor/main.js\"></script>\n");
      out.write("<script src=\"/web/resources/js/reservation/vendor/swiper.min.js\"></script>\n");
      out.write("<script src=\"/web/resources/js/homemain/nav.js\"></script>\n");
      out.write("\n");
      out.write("<!-- newfeedjs -->\n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/wow.min.js\"></script>      \n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/respond.min.js\"></script>    \n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/html5shiv.min.js\"></script>\t\n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/custom.js\"></script>     \n");
      out.write("<!-- instanavjs -->\n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/instanav.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/instafeed.js\"></script> <!-- instafeed.js 추후 미사용시 삭제. -->\n");
      out.write("<!-- instajs -->\n");
      out.write("<!-- Stickyjs --->\n");
      out.write("<script type=\"text/javascript\" src=\"/web/resources/js/aquagram/vendor/Sticky-kit.js\"></script>\n");
      out.write("<!-- commonjs -->\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/app.js\"></script>\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/router.js\"></script>\n");
      out.write("<!-- jieunjs -->\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/component/jecompo.js\"></script>\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/admin/jieun.js\"></script>\n");
      out.write("<!-- eunyeongjs -->\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/component/eycompo.js\"></script>\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/reservation/eunyeong.js\"></script>  \n");
      out.write("<!-- jeongukjs -->\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/component/jwcompo.js\"></script>\n");
      out.write("<script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/js/aquagram/jeonguk.js\"></script>  \n");
      out.write("<!-- 낚어안녕 -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("app.init('");
      out.print( application.getContextPath() );
      out.write("');\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
